### PR TITLE
Replace storage implementation with Moneta gem for simple key/value storage

### PR DESCRIPTION
**Pull request by brutuscat**
Replace storage implementation with Moneta gem for simple key/value storage

This way the support for many storage options is transferred to the Moneta gem.
Many methods were deprecated, since Moneta does not support them (yet):
- `each`, `keys` & `values`, `size` and `merge!` are gone
- page storage `uniq!`, `pages_linking_to` and `urls_linking_to` are gone too

Default storage uses an in memory LRU-Hash implementation (Moneta default) with a max of 1Gb by default (configurable via Moneta options)
## Work In Progress - TODO
- [X] Replace custom key/value storage with Moneta gem
- [X] Fix specs
- [ ] Redo cli tools with user land algorithms to replace missing page storage methods
- [ ] Write docs & examples on how to use, at the least, the already supported storage options
- [x] Add an `each_key` method in Moneta for the storage adapters that would support it (see https://github.com/minad/moneta/issues/61, minad/moneta#134, minad/moneta#136)

### CODE REVIEW

**Comment by MothOnMars** [comment]
@brutuscat , are you still planning to use Moneta for the page store? I've been using Medusa quite a bit recently, and looking at this PR, I've realized that I'd lose some of the functionality I depend on if those storage methods were deprecated (particularly `urls_linking_to`). Would you be open to a lighter-weight PR that would simply:
- remove the storage options that no longer appear to be supported (Tokyo Cabinet, Kyoto Cabinet)
- update the code to use MongoDB 3.+

Moneta still does not support iteration. The changes I suggest would serve to simplify (ok, limit) the storage options, but Medusa could still swap out the remaining storages in the future if/when Moneta adds iteration support. That would make Medusa easier to develop on in the short term, without sacrificing any usability. Thoughts?

**Comment by brutuscat** [comment]
@MothOnMars not really, the idea is to decouple Medusa from any storage implementation. The urls_linking_to could be moved to your app code instead using the API provided by Moneta. 

This is sort of blocked on me implementing "each" in Moneta, so you do have the ability to implement the BFS or DFS to algorithm as needed by your app. It will be a breaking change, yes.

**Comment by MothOnMars** [comment]
Makes sense. Thanks.

**Comment by asppsa** [comment]
Heya, just thought I'd let you know that moneta 1.1.0 finally got released with `each_key` support (called "key traversal" in the docs) - a big thank you to @brutuscat for making that happen.  The [backend feature matrix on Rubydoc.info](https://www.rubydoc.info/gems/moneta#Backend_feature_matrix) lists the adapters that can do key traversal.

**Comment by brutuscat** [comment]
Closing in favor of #14

**Pull request closed without merging**
